### ISSUE TITLE
Use GTranslate to speed up the translation

### ISSUE THREAD

**Issue by David-Maisonave** [stevencohn/ResxTranslator#1]
Hi,
Great job!
I went through about a dozen GitHub projects, before finding this one, which actually does what I expected.

However it runs slow when doing 10 or more languages translation.  I recommend using GTranslate to speed up the process.
That's what I'm using in my C# GitHub project ([TranslateFileNames](https://github.com/David-Maisonave/TranslateFileNames)).
Using GTranslate I can translate 89 files in less then 2 seconds.

I've downloaded this project, and if you'll except the changes, I can try adding GTranslate to ResxTranslator.
I can also add an install project to the solution that will create an install for ResxTranslator.

FYI:
I did see one bug, where the output went to the same folder where the original resx file was located instead of the sub folder I added to the Output directory field.
I'll see if I can fix that too.

**Comment by David-Maisonave** [comment]
I created a program that's loosely based on the ResxTranslator GUI.

[https://github.com/David-Maisonave/ABetterTranslator](https://github.com/David-Maisonave/ABetterTranslator)

It's using GTranslate, and it can translate an Resx file to 131 different languages in less then 60 seconds.
I've tested it with an Resx file that has 77 strings.

I've also built [ABetterTranslator](https://github.com/David-Maisonave/ABetterTranslator) with the Resx files that were translated, so the program also runs in 131 different languages.

You can use the following link to download the installer.
[https://github.com/David-Maisonave/ABetterTranslator/releases/latest](https://github.com/David-Maisonave/ABetterTranslator/releases/latest)

**Comment by stevencohn** [comment]
GTranslate indeed looks very good. I noticed the translations are different than those provided by the old Google API. I can barely speak my own language let alone all the others so I've no idea which is better but I can only presume these services are acceptable to native speakers.

Thanks for letting me know about GTranslate.
